### ISSUE TITLE
LiveQuery server URI is missing, when connecting to back4app service

### ISSUE THREAD

**Issue by cristi-zz** [nataliaconde/android-live-query-simple#1]
Hi!

In line 55 from [LogoutActivity.java](https://github.com/nataliaconde/android-live-query-simple/blob/b88e71bded0755469c890057d458452a6a74f67f/app/src/main/java/com/example/back4app/userregistrationexample/LogoutActivity.java#L55) one must specify an URI server to connect to:

```ParseLiveQueryClient.Factory.getClient();``` should be ```ParseLiveQueryClient.Factory.getClient(new URI("wss://my-magic-back4app.back4app.io/"));``` or equivalent, to connect to back4app provider.

I would recommend to remove the comment, and add a proper text resource in ```strings.xml```. Also, update ```readme``` to notify the user that she/he must also change the ```wss``` server address.

I spent ~3 endless hours debugging this, that's why I recommend this clarification

Cheers,
Cristi

**Comment by nataliaconde** [comment]
Hi! Thanks for your feedback regarding these problems, I fixed and upload the changes made.

**Comment by nataliaconde** [comment]
Hi! Thanks for your feedback regarding these problems, I fixed and upload the changes made.
